name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: [ "main" ] # Hoặc master tùy tên branch của bạn

# Cấp quyền cho GitHub Actions deploy lên Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build dự án
        run: npm run build

      - name: Upload sản phẩm đã build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Thư mục đầu ra của Vite

      - name: Deploy lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
